version:'3'version: "3.8"
services:
  backend:
    build: ./backend
    image: monitoring-backend:local
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: monitoring-frontend:local
    ports:
      - "3000:80"
    depends_on:
      - backend
