apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: monitor-app
spec:
  selector:
    app: monitoring-backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
