apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: monitor-app
spec:
  selector:
    app: monitoring-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30050
  type: NodePort
