apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: monitor-app
spec:
  selector:
    app: monitoring-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
